/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chmelonLogoMetal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Frozen white metal']}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.271, -0.021, -0.271]}
      />
    </group>
  )
}

useGLTF.preload('/chmelonLogoMetal.glb')
